name: preview

on: [push, pull_request]

jobs:
  release:
    name: Release preview build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version: 22.x

      - name: Install dependencies
        run: npm i

      - name: Build
        run: npm run build